site_name: self-dsl
theme: readthedocs
markdown_extensions:
 - codehilite
 - plantuml
 - shellcmd
 - namedref
pages:
 - 'index.md'
 - 'motivation.md'
 - 'basics.md'
 - Xtext:
    - {'Eclipse':'xtext_eclipse.md'}
    - {'Xtext Project Setup':'xtext_project_setup.md'}
    - {'A First Grammar':'xtext_a_first_grammar.md'}
#    - {'Auto Formatting':'xtext_auto_formatting.md'}
    - {'Code Generation (with Xtend)':'xtext_code_generation_xtend.md'}
    - {'Model Validation':'xtext_model_validation.md'}
#    - {'Quickfixes':'xtext_quickfixes.md'}
    - {'Xtend: Selected Aspects':'xtext_xtend.md'}
    - {'Scoping':'xtext_scoping.md'}
    - {'Modularization':'xtext_modularization.md'}
    - {'Deploy a command line version':'xtext_deploy_command_line.md'}
    - {'Deploy an eclispe plugin':'xtext_deploy_plugin.md'}
    - {'Xtext HOWTOs':'xtext_howtos.md'}
 - TextX:
    - {'TextX Intro':'textx_intro.md'}
    - {'TextX Project Setup':'textx_project_setup.md'}
    - {'TextX by Examples':'textx_by_examples.md'}
 - 'references.md'


